name: build-test
'on':
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Install buf
        uses: bufbuild/buf-setup-action@v0.6.0
      - name: Install libgit2
        run: |
          sudo apt-get install libssh2-1-dev libssl-dev cmake && \
          wget https://github.com/libgit2/libgit2/archive/refs/tags/v1.3.0.tar.gz && \
          tar xzf v1.3.0.tar.gz && \
          cd libgit2-1.3.0/ && \
          mkdir build && cd build && \
          cmake .. && \
          make && \
          sudo make install
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.44.2
      - name: Install dependencies
        run: make .install
      - name: Run linters
        env:
          LD_LIBRARY_PATH: '/usr/local/lib'
        run: make lint
      - name: Run tests
        env:
          LD_LIBRARY_PATH: '/usr/local/lib'
        run: make test
