name: "Test json inputs"
'on':
  pull_request:
    branches:
      - main
jobs:
  create-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: set json
        id: json
        run: |
          echo "::set-output name=matrix::$(cat test.json)"
    outputs:
      matrix: ${{ steps.json.outputs.matrix }}

  test-json:
    needs: [create-json]
    runs-on: ubuntu-latest
    steps:
      - name: set
        run: |
          echo "${{fromJSON(needs.github_convertor.outputs.matrix)}}"
          VAR=${{fromJSON(needs.github_convertor.outputs.matrix)}}
          echo $VAR

  printstuff:
    needs: [create-json]
    strategy:
      matrix: 
        data: ${{fromJSON(needs.github_convertor.outputs.matrix)}}
    runs-on: ubuntu-latest
    steps:
      - if: matrix.data.truebool 
        run: echo truebool
      - if: matrix.data.falsebool 
        run: echo falsebool
      - if: matrix.data.falsestring == 'false'
        run: echo falsestring
      - if: matrix.data.truestring == 'true' 
        run: echo truestring
      - if: matrix.data.key1 != '' 
        run: echo key1 exists with values ${{ matrix.data.key1 }}
      - if: matrix.data.key2 != '' 
        run: echo key2 exists with values ${{ matrix.data.key2 }}
 



